// <auto-generated />
namespace PRUEBA_TECNICA_IMOVS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TablasIniciales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablasIniciales));
        
        string IMigrationMetadata.Id
        {
            get { return "202509111915305_TablasIniciales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
